### ISSUE TITLE
We need some docs/notes for Clean as well

### ISSUE THREAD

**Issue by Ali-TM-original** [codeapples/treasure-box#1]
Well clean really messes with students brain. So this issue will be for that

**Comment by peterkmg** [comment]
You can try and add some things about functional as you see fit, and I will also take part.

Have a look at https://mermaid.js.org/ you can use mermaid syntax to make some cool diagrams now. Which would come in handy for trees n stuff.

I'm still working on adding more plugins to markdown and possibly improving the base, after that I will dig into more materials, so at the end we have at least imperative+functional+math+programming covered completely. Maybe even compsys if we find a volunteer, cuz I won't do that one :)

**Comment by peterkmg** [comment]
Clean was replaced by haskell
